---
fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v8.0.0'
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat.git'
      ref: 'v7.0.0'
    sshkeys:
      repo: 'https://github.com/puppetlabs/puppetlabs-sshkeys_core.git'
      ref: 'v2.3.0'
